### ISSUE TITLE
Liveliness/readiness probe - bridge container being recycled

### ISSUE THREAD

**Issue by VaclavK** [Azure/Bridge-To-Kubernetes#111]
**Describe the bug**
Container with liveliness (readiness) probe - when connected to, probe is not removed from the spec, container will be restarted in a loop

**Mention the platform you are using**
VS 2022 Enterprise - 17.4

**To Reproduce**

Service spec has a liveliness probe e.g.

```yaml
livenessProbe:
      httpGet:
        path: /health
        port: 3000
      initialDelaySeconds: 5
      periodSeconds: 5
```

Connect bridge in VS.. this overwrites service spec to point to bridge container image
probe is not "disabled"
K8 attempts check the probe, this fails against the bridge image and container is being restarted

**Expected behavior**

liveliness/readiness probe "parked" and restored when the bridge is disconnected

or 

document the limitation - I can't see currently any limitation documented re this

**Desktop (please complete the following information):**
 - OS: W10
