### ISSUE TITLE
Unable to download '/var/run/secrets/kubernetes.io/serviceaccount' volume via KubernetesLocalProcessConfig

### ISSUE THREAD

**Issue by jun10k** [Azure/Bridge-To-Kubernetes#152]
**Describe the bug**
Bridge is trying download the volume which is already terminated.

**Mention the platform you are using**
Visual Studio Code: 1.74.3
Bridge to Kubernetes: v2.0.120230118
Kubernetes: v1.3.11

**To Reproduce**
1. Have a k8s cluster up and running
2. Create service in default namespace with 1 replica in deployment **e.g. demo-69cb64bdf6-z8zt7 with the volume kube-api-access-mxfdk**  
3. Config local tunnel debugging with the created service
4. Try the debugging in VSCode and make sure it works well 
5. Create **KubernetesLocalProcessConfig.yaml** file as 
```yaml
version: 0.1
volumeMounts:
  - name: kube-api-access-*
    localPath: /var/run/secrets/kubernetes.io/serviceaccount
env:
  - name: KUBERNETES_IN_CLUSTER_CONFIG_OVERRIDE
    value: $(volumeMounts:kube-api-access-*)
```
6. Retry the debugging again.
7. In the terminal, the Bridge will recreate the pod (**e.g. demo-6fbdff95c9-qbs6k**) for debugging, which has difference name of volume kube-api-access-hzggh
8. Bridge was still trying to download volume from volume kube-api-access-mxfdk
```shell
Service 'kubernetes' is available on 127.1.1.1:443.
Container port 8080 is available at localhost:8081.
Downloading volume 'kube-api-access-mxfdk' from '/var/run/secrets/kubernetes.io/serviceaccount' ...
Downloading from '/var/run/secrets/kubernetes.io/serviceaccount' ...
Download failed with error: Access to the path '/var/run/secrets/kubernetes.io/serviceaccount' is denied.
Retrying ...
Download failed with error: Access to the path '/var/run/secrets/kubernetes.io/serviceaccount' is denied.
```

**Expected behavior**
Bridge should get the correct the volume name to download when recreated the new pod for debugging.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac 12.6
 - kind v0.16.0 go1.19.1 darwin/arm64

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A
