### ISSUE TITLE
Question on Volume

### ISSUE THREAD

**Issue by maxisam** [Azure/Bridge-To-Kubernetes#177]
I read the document and I am not sure if I misunderstand anything here

according to https://learn.microsoft.com/en-us/visualstudio/bridge/configure-bridge-to-kubernetes

The only way to mount the volume is download it and set the path to environment variable?

```
version: 0.1
env:
  - name: ALLOW_LIST_PATH
    value: $(volumeMounts:allow-list)/allow-list
```

Is there a way to use the volume mount without downloading ? It seems like not very practical if my volume is huge.

Thanks
