### ISSUE TITLE
Don't try to bind port 80 when it's not needed

### ISSUE THREAD

**Issue by carlin-q-scott** [Azure/Bridge-To-Kubernetes#207]
**Describe the bug**
It tries to bind to port 80 even though my container, pod and service aren't using port 80.

**Mention the platform you are using**
Visual Studio Professional 2022

**To Reproduce**
service.yaml:
```yaml
  ports:
  - name: http
    port: 9080
    protocol: TCP
    targetPort: 9080
  - name: https
    port: 9081
    protocol: TCP
    targetPort: 9081
```

pod.yaml:
```yaml
ports:
- containerPort: 9080
  name: http
  protocol: TCP
- containerPort: 9081
  name: https
  protocol: TCP
```

Dockerfile:
```Dockerfile
EXPOSE 9080
EXPOSE 9081
```

launchSettings.json
```json
{
  "profiles": {
    "Project": {
      "commandName": "Project",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      },
      "applicationUrl": "http://localhost:9080;https://localhost:9081"
    },
    "Docker": {
      "commandName": "Docker",
      "launchBrowser": true,
      "launchUrl": "{Scheme}://{ServiceHost}:{ServicePort}/health",
      "publishAllPorts": true,
      "DockerfileRunArguments": ""
    },
    "Bridge to Kubernetes": {
      "commandName": "AzureDevSpacesLocal",
      "launchBrowser": true,
      "httpPort": 9080,
      "sslPort": 9081
    }
  }
}
```

**Expected behavior**
It should have bound to port 9080/9081

**Screenshots**
![image](https://user-images.githubusercontent.com/2521644/225773528-c6872b11-d39a-4ec5-82ab-001b05177895.png)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro 22H2
 - Browser: Edge 111.0.1661.41
 - B2K: 3.2.20230314.5

**Additional context**
Relates to #189
