### ISSUE TITLE
Support for sidecar containers

### ISSUE THREAD

**Issue by maurice-freitag** [Azure/Bridge-To-Kubernetes#233]
Most of our microservices run multiple containers in a pod, usually the service itself, as well as sidecar containers running Dapr and [Open Policy Agent](https://www.openpolicyagent.org/), specifically through an [OPAL client](https://www.opal.ac/). Dapr communication works fine as there is some specialilized logic in this repo handling it, e.g. in [WorkloadInformationProvider](https://github.com/Azure/Bridge-To-Kubernetes/blob/main/src/library/Connect/WorkloadInformationProvider.cs). Trying to access the OPA via localhost however does not work. 

Either VSCode or VS extension support or some documentation for workarounds would be nice. Ideally there should be a generic way to support sidecar containers.

**Comment by nagisatosanae** [comment]
I don't know if this is the correct way to do it, but I used KubernetesLocalProcessConfig to verify the behavior.

For example, if you create a dapr app with the alicebob app-id and the alice 
container is binded to dapr's app-port of dapr, bob will be a sidecar.

This is the YAML we used for testing.
```
apiVersion: v1
kind: Service
metadata:
  name: alicebob
spec:
  selector:
    app: alicebob
  ports:
  - protocol: TCP
    port: 3030
    name: alice
    targetPort: 3030
  - protocol: TCP
    port: 4040
    name: bob
    targetPort: 4040
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alicebob
  namespace: ncp-bridge
spec:
  selector:
    matchLabels:
      app: alicebob
  replicas: 1
  template:
    metadata:
      labels:
        app: alicebob
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "alicebob"
        dapr.io/log-level: "debug"
        dapr.io/app-port: "3030"
        dapr.io/enable-api-logging: "true"
        dapr.io/sidecar-listen-addresses: "[::],0.0.0.0"
    spec:
      containers:
      - image: harbor.sailio.ncsoft.com/espark/node-alice:latest
        name: alice
        ports:
        - containerPort: 3030
      - image: harbor.sailio.ncsoft.com/espark/node-bob:latest
        name: alice
        ports:
        - containerPort: 4040
```

Run dsc

`dsc connect --service alicebob --local-port 4040 --namespace default --container bob`

I've tested it, but I don't know, this is the right way?

**Comment by nagisatosanae** [comment]
I too was wondering if sidecar integration is possible.
It looks like a trick, but I tried it like below and confirmed the behavior.
But I don't know if this is the right way or if there are any side effects.
Could you please check right way?

Let's suppose app called foobar, foo is the main app bar is the sidecar.


1. KubernetesLocalProcessConfig.yaml
```
version: 0.1
env:
  - name: FOOBAR_SERVICE_HOST
    value: $(services:foobar)
```


2. Service와 Deployment yaml
```
apiVersion: v1
kind: Service
metadata:
  name: foobar
spec:
  selector:
    app: foobar
  ports:
  - protocol: TCP
    port: 3030
    name: foo
    targetPort: 3030
  - protocol: TCP
    port: 4040
    name: bar
    targetPort: 4040
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foobar
spec:
  selector:
    matchLabels:
      app: foobar
  replicas: 1
  template:
    metadata:
      labels:
        app: foobar
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "foobar"
        dapr.io/log-level: "debug"
        dapr.io/app-port: "3030"
        dapr.io/enable-api-logging: "true"
        dapr.io/sidecar-listen-addresses: "[::],0.0.0.0"
    spec:
      containers:
      - image: docker/node-alice:latest
        name: foo
        ports:
        - containerPort: 3030
        imagePullPolicy: Always
      - image: docker/node-bob:latest
        name: bar
        ports:
        - containerPort: 4040
```

3. dsc run
dsc connect --service foobar --local-port 4040 --namespace default --container bar
