### ISSUE TITLE
Bridge is crashed if UDP svc at namespace. (Index was outside the bounds error)

### ISSUE THREAD

**Issue by Rverkh** [Azure/Bridge-To-Kubernetes#234]
**Describe the bug**
Bridge doesn't work if we have UDP service (svc) at namespace where we are trying to replace application with Bridge.
An unexpected error occurred: 'Index was outside the bounds of the array.'

As far as I know kubectl doesn't support UDP port-forward yet. But may be it's possible to just ignore UDP svc and write some warnings at that case?

**Mention the platform you are using**
Reproduced with vscode extension and cli tool

**To Reproduce**
1. Deploy tcp based application
2. Deploy any udp based application at the same namespace
3. Make svc's for both
4. Launch b2k for tcp application and it will fault with "An unexpected error occurred: 'Index was outside the bounds of the array.'" error

Here is some simple example of pod and svc
```
apiVersion: v1
kind: Pod
metadata:
  name: sample-udp-listener
  labels:
    name: sample-udp-listener
  namespace: udp-example
spec:
  containers:
    - name: "sample-udp-listener"
      image: "alpine"
      command: ["/usr/bin/nc"]
      args: [ "-u", "-l","2115"]
      ports:
        - containerPort: 2115
          protocol: UDP
---
apiVersion: v1
kind: Pod
metadata:
  name: sample-tcp-listener
  labels:
    name: sample-tcp-listener
  namespace: udp-example
spec:
  containers:
    - name: "sample-tcp-listener"
      image: "alpine"
      command: ["/usr/bin/nc"]
      args: [ "-lk", "-e","2116"]
      ports:
        - containerPort: 2116
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sample-udp-svc
  name: sample-udp-svc
  namespace: udp-example
spec:
  ports:
  - port: 2115
    protocol: UDP
    targetPort: 2115
  selector:
    name: sample-udp-listener
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: sample-tcp-svc
  name: sample-tcp-svc
  namespace: udp-example
spec:
  ports:
  - port: 2116
    protocol: TCP
    targetPort: 2116
  selector:
    name: sample-tcp-listener
  type: ClusterIP
```

Then you can launch 

```
./dsc connect --service sample-tcp-svc --local-port 3116  --namespace udp-example --use-kubernetes-service-environment-variables


Waiting for 'sample-tcp-listener' in namespace 'udp-example' to reach running state...
Pod 'sample-tcp-listener' created in namespace 'udp-example'.
Remote agent deployed in container 'sample-tcp-listener' in pod 'sample-tcp-listener'.
Preparing to run Bridge To Kubernetes configured as pod udp-example/sample-tcp-listener ...
Connection established.
Service 'sample-tcp-svc' is available on 127.0.0.1:55049.
Container port 2116 is available at localhost:3116.
Connect operation failed.
Stopping workload and cleaning up...
Restore: Pod 'sample-tcp-listener' deleted.
Restore: Pod 'sample-tcp-listener' restored to original state.
An unexpected error occurred: 'Index was outside the bounds of the array.'
To see our active issues or file a bug report, please visit https://aka.ms/bridge-to-k8s-report.
For diagnostic information, see logs at '/tmp/Bridge To Kubernetes'.
```
**Expected behavior**
Running bridge with maybe some warnings about udp svc forwarding not supported

**Desktop (please complete the following information):**
 - OS: Ubuntu 5.15.90.1-microsoft-standard-WSL2 (Reproduced with Windows extension as well)
 - cli tool: 1.0.20230310.3
 - vscode extension: v2.0.120230327

**Additional context**
Logs from cli tool
[bridge-library-2023-04-03-11-18-49-22176.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/11137702/bridge-library-2023-04-03-11-18-49-22176.txt)
[bridge-mindarocli-2023-04-03-11-18-48-22176.txt](https://github.com/Azure/Bridge-To-Kubernetes/files/11137703/bridge-mindarocli-2023-04-03-11-18-48-22176.txt)
