### ISSUE TITLE
Envoy pods no longer apply `kubernetes-route-as` header via ingress route from routingmanager:20220811.1

### ISSUE THREAD

**Issue by scp-mb** [Azure/Bridge-To-Kubernetes#49]
**Describe the bug**
Since the image `routingmanager:20220811.1` (`routingmanager:20220803.1` works) was released the ConfigMap for envoy pods no longer applies the `kubernetes-route-as` header when accessing a b2k pod through an ingress route. Setting the header manually (e.g. via postman request) still works as expected.

Note, we have two ingress per api. ConfigMaps below have been sanitized to remove identifying information.

Working envoy ConfigMap from `routingmanager:20220803.1`:

```
static_resources:
  listeners:
  - name: listener_80_80
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    listener_filters:
    - name: envoy.filters.listener.http_inspector
    filter_chains:
    - filter_chain_match:
        application_protocols:
        - http/1.0
        - http/1.1
        - h2c
      filters:
      - name: envoy.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: listener_80_80
          route_config:
            name: listener_80_80_route
            virtual_hosts:
            - name: listener_80_80_route_ingress_withDomain_b2ktest.apiname.sub2.company.net
              domains:
              - b2ktest.apiname.sub2.company.net
              routes:
              - match:
                  prefix: /
                route:
                  cluster: service_debug_withHeader_kubernetes-route-as_b2ktest_80_80
                  timeout: 0s
                  idle_timeout: 0s
                request_headers_to_add:
                - header:
                    key: kubernetes-route-as
                    value: b2ktest
                  append: false
            - name: listener_80_80_route_ingress_withDomain_b2ktest.apiname.sub1.company.net
              domains:
              - b2ktest.apiname.sub1.company.net
              routes:
              - match:
                  prefix: /
                route:
                  cluster: service_debug_withHeader_kubernetes-route-as_b2ktest_80_80
                  timeout: 0s
                  idle_timeout: 0s
                request_headers_to_add:
                - header:
                    key: kubernetes-route-as
                    value: b2ktest
                  append: false
            - name: listener_80_80_route_default
              domains:
              - '*'
              routes:
              - match:
                  headers:
                  - name: kubernetes-route-as
                    exact_match: b2ktest
                  prefix: /
                route:
                  cluster: service_debug_withHeader_kubernetes-route-as_b2ktest_80_80
                  timeout: 0s
                  idle_timeout: 0s
              - match:
                  prefix: /
                route:
                  cluster: service_original_clone_80_80
                  timeout: 0s
                  idle_timeout: 0s
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: service_original_clone_80_80
    connect_timeout: 1.00s
    type: strict_dns
    load_assignment:
      cluster_name: service_original_clone_80_80
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: apireleasename-cloned-routing-svc.apireleasename
                port_value: 80
    http_protocol_options: {}
  - name: service_debug_withHeader_kubernetes-route-as_b2ktest_80_80
    connect_timeout: 1.00s
    type: static
    load_assignment:
      cluster_name: service_debug_withHeader_kubernetes-route-as_b2ktest_80_80
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.240.1.253
                port_value: 80
    http_protocol_options: {}
admin:
  access_log_path: /tmp/admin_access.log
```

Non-working envoy ConfigMap from `routingmanager:20220811.1`, note the missing section per ingress under `virtual_hosts` for the ingress routes:

```
  static_resources:
  listeners:
  - name: listener_80_80
    address:
      socket_address:
        address: 0.0.0.0
        port_value: 80
    listener_filters:
    - name: envoy.filters.listener.http_inspector
    filter_chains:
    - filter_chain_match:
        application_protocols:
        - http/1.0
        - http/1.1
        - h2c
      filters:
      - name: envoy.http_connection_manager
        typed_config:
          '@type': type.googleapis.com/envoy.extensions.filters.network.http_connection_manager.v3.HttpConnectionManager
          codec_type: auto
          stat_prefix: listener_80_80
          route_config:
            name: listener_80_80_route
            virtual_hosts:
            - name: listener_80_80_route_default
              domains:
              - '*'
              routes:
              - match:
                  headers:
                  - name: kubernetes-route-as
                    exact_match: b2ktest
                  prefix: /
                route:
                  cluster: service_debug_withHeader_kubernetes-route-as_b2ktest_80_80
                  timeout: 0s
                  idle_timeout: 0s
              - match:
                  prefix: /
                route:
                  cluster: service_original_clone_80_80
                  timeout: 0s
                  idle_timeout: 0s
          http_filters:
          - name: envoy.filters.http.router
  clusters:
  - name: service_original_clone_80_80
    connect_timeout: 1.00s
    type: strict_dns
    load_assignment:
      cluster_name: service_original_clone_80_80
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: apireleasename-cloned-routing-svc.apireleasename
                port_value: 80
    http_protocol_options: {}
  - name: service_debug_withHeader_kubernetes-route-as_b2ktest_80_80
    connect_timeout: 1.00s
    type: static
    load_assignment:
      cluster_name: service_debug_withHeader_kubernetes-route-as_b2ktest_80_80
      endpoints:
      - lb_endpoints:
        - endpoint:
            address:
              socket_address:
                address: 10.240.1.253
                port_value: 80
    http_protocol_options: {}
admin:
  access_log_path: /tmp/admin_access.log
```

**Mention the platform you are using**
Helm deployments via azure devops to spin up temporary test environments

**To Reproduce**
Set up two namespaces with routingmanager deployed, an api and an ingress. Use version `routingmanager:20220811.1` and `20220803.1`. Make a request to isolated subdomain and note traffic goes to normal pod, not b2k pod.

**Expected behavior**
`kubernetes-route-as` header should be applied by envoy pods to any request that hits the isolated subdomain

**Screenshots**
![image](https://user-images.githubusercontent.com/52526733/189636965-1c1eb24d-3233-4f65-919e-4b80df0fd84e.png)

**Additional context**
Redacted output from `kubectl get ingress` for one of the affected ingress routes

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: apireleasename
    meta.helm.sh/release-namespace: apireleasename
  creationTimestamp: "2022-04-21T16:24:11Z"
  generation: 1
  labels:
    app: apireleasename
    app.kubernetes.io/managed-by: Helm
    chart: apireleasename-0.1.0
    heritage: Helm
    release: apireleasename
  name: apireleasename
  namespace: apireleasename
  resourceVersion: "138231846"
  uid: a18a6e6f-280b-4d82-8460-398c81642a25
spec:
  ingressClassName: nginx
  rules:
  - host: api.sub2.company.net
    http:
      paths:
      - backend:
          service:
            name: apireleasename
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api.sub2.company.net
    secretName: wildcard-sub2-review-apps-cert
status:
  loadBalancer:
    ingress:
    - ip: <redacted>
```

**Comment by hsubramanianaks** [comment]
@scp-mb Hi Thank you for your patience, we are unable to reproduce this issue using following image `routingmanager:20220811.1`. I tried with sample ingress app which is present [here](https://github.com/Azure/Bridge-To-Kubernetes/tree/main/samples/ingress). 

The latest routing manager image is `routingmanager:20220817.1`, please try with this image and let us know if it works.

**Comment by scp-mb** [comment]
@hsubramanianaks Using the latest stable I still have the same issue, but I've done a little bit more digging and found the issue is similar to #25 and @letmagnau found the problem too

There's an error log entry in the `routingmanager` logs that I must have missed/overlooked the first time around:
`2022-09-28T08:55:14.3683001Z | RoutingManager | ERROR | Service port 'null' from ingress 'ingressname' does not match any port on the service 'servicename'. `

As noted above, the ingress uses `port.number: 80`.
The service defines ports as follows:

```
ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
```

Changing the ingress in the original post to use a port name instead of a port number seems to fix the envoy pod configuration, for example:

```
- backend:
    service:
      name: apireleasename
      port:
        name: http
```

I presume this is still a bug and numeric ports should be usable instead of just named ports even if the service port is named? I see that the example service for todoapp doesn't give the port a name on the service so that could be why you can't reproduce the issue?
