### ISSUE TITLE
Support for Azure AD Workload Identity?

### ISSUE THREAD

**Issue by Eneuman** [Azure/Bridge-To-Kubernetes#61]
Will B2K support Azure AD Workload Identity?

**Comment by qpetraroia** [comment]
Hi @Eneuman,

Thanks for reaching out. The team is wondering if you could potentially give us a bit more information into the ask. Have you tried Bridge with AD Workload Identity? Did it not work? Can you give us steps to reproduce the issue? Thanks!

**Comment by Eneuman** [comment]
Hi

I think you need to download the mount by setting a config in KubernetesLocalProcessConfig.yaml
Somethink like: 

volumeMounts:
  - name: azure-identity-token
    localPath: /var/run/secrets/azure/tokens
env:
  - name: AZURE_FEDERATED_TOKEN_FILE
    value: $(volumeMounts:azure-identity-token)

I havnt had the time to test this yet so please let me know how it goes :)

**Comment by Eneuman** [comment]
@elenavillamil Unfortunately I haven't had the time yet. I did some poking around a while ago and I think I found one issue that probably needs to be solved.

The download of the mount will only work if the token has already been created, but if this is the first time you start your app, the token will be created after the download has occurred, so some sort of mount download "sync" might be needed.

**Comment by elenavillamil** [comment]
I was able to get a scenario that uses this and I can confirm bridge does not work with it as it is. Our MI "dummy" service currently only supports get requests. I have noticed when Azure AD is used it uses POST request and our code does not handle it properly and service sees not authorized. We should add this work to our planing.

**Comment by elenavillamil** [comment]
@VaclavK apologies for the late reply. Could you try syncing the volume and setting the env variable using b2k config file. From this [WorkloadIdentity documentation](https://blog.identitydigest.com/azuread-federate-k8s/), when you do describe on your pod you should see something like:
```
- name: AZURE_FEDERATED_TOKEN_FILE
          value: /var/run/secrets/tokens/azure-identity-token
        volumeMounts: 
        - mountPath: /var/run/secrets/tokens
            name: azure-identity-token
```

B2K allows you to sync volumes. Documentation on this [here](https://learn.microsoft.com/en-us/visualstudio/bridge/configure-bridge-to-kubernetes#download-a-volume). I believe something like below should work. Not that I made this path up, this is where you tell it to download the mount on your local machine, so please update as needed, but make sure the folder exists before connecting bridge. If you have issues setting it up let me know.

```
volumeMounts:
  - name: azure-identity-token
    localPath: /tmp/b2k/tokens/azure-identity-token

env:
  - name: AZURE_FEDERATED_TOKEN_FILE
    value: $(volumeMounts:azure-identity-token)
 
```

**Comment by MichaelPetrinolis** [comment]
Hi, I run on the exact same issue. I configured the mounted volume, and I get the following error:
"Azure.Identity.AuthenticationFailedException: ClientAssertionCredential authentication failed: Access to the path 'C:\var\run\secrets\azure\tokens\azure-identity-token' is denied."

**Comment by MichaelPetrinolis** [comment]
After some investigation, I managed to make it work. Use the following KubernetesLocalProcessConfig.yaml for your project, if you have enabled the Workload Identity
```yaml
version: 0.1
enableFeatures:
  - ManagedIdentity

volumeMounts:
  - name: azure-identity-token
    localPath: /tmp/tokens/pod_name

env:
  - name: AZURE_FEDERATED_TOKEN_FILE
    value: $(volumeMounts:azure-identity-token)/azure-identity-token
```

**Comment by MichaelPetrinolis** [comment]
Hi @hsubramanianaks, I can confirm that it works, there is no need for the enableFeatures entry. 
It only needs the volume mount and the env variable. The DefaultAzureCredential (v1.9.0 - 1.8.2 does not work) works just fine.
```yaml
version: 0.1

volumeMounts:
  - name: azure-identity-token
    localPath: /tmp/tokens/pod_name

env:
  - name: AZURE_FEDERATED_TOKEN_FILE
    value: $(volumeMounts:azure-identity-token)/azure-identity-token
```
