### ISSUE TITLE
Unable to connect to EKS cluster using VS2022 plugin

### ISSUE THREAD

**Issue by plaisted** [Azure/Bridge-To-Kubernetes#71]
**Describe the bug**
VS2022 B2K plugin is unable to read kubeconfig file for EKS.

**Mention the platform you are using**
VS2022
B2K 3.0.20220912.3

**To Reproduce**
1. Install extension
2. Switch to B2K launch profile
3. Launch debugger or open debug properties -> Edit profile for Bridge To Kubernetes
4. See error "Failed to load current kubeconfig. This could be due to a typo in your kubeconfig or to an unsupported configuration. ..."

**Expected behavior**
B2K reads kubeconfig properly

**Additional context**

I've tried with both the default EKS connection setup (using kubeconfig exec config to create token on demand) and hardcoded bearer as shown below. Both work without issue for kubectl and other apps.

kubeconfig
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0t<redacted>
    server: https://<redacted>.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:<redacted>:cluster/<redacted>
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:<redacted>:cluster/<redacted>
    namespace: argocd
    user: arn:aws:eks:us-east-1:<redacted>:cluster/<redacted>
  name: arn:aws:eks:us-east-1:<redacted>:cluster/<redacted>
current-context: arn:aws:eks:us-east-1:<redacted>:cluster/<redacted>
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:<redacted>:cluster/<redacted>
  user:
    token: k8s-aws-v1.aHR<redacted>

```

https://github.com/microsoft/mindaro/issues/129
https://github.com/microsoft/mindaro/issues/126
